# local_backend: true
backend:
  name: github
  repo: robinlrx/tino-pizz
  branch: use-sveltia-cms

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "pizza"
    label: "Pizza"
    folder: "src/content/pizza"
    create: true
    identifier_field: "name"
    extension: "json"
    format: "json"
    fields:
      - label: "Base"
        name: "base"
        widget: "select"
        options:
          - "Tomate"
          - "Crème fraîche"
          - "Sucrée"
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Ingrédients", name: "ingredients", widget: "string" }
      - label: "Prix 26 cm"
        name: "price26"
        widget: "number"
        value_type: "float"
        step: 0.01
        required: false
        condition:
          field: "base"
          value: "Sucrée"
          operator: "!="
      - { label: "Prix 31 cm", name: "price31", widget: "number", value_type: "float", step: 0.01 }

  - name: "tour"
    label: "Tournée de la semaine"
    folder: "src/content/tour"
    create: true
    summary: "{{weekday}} - {{adress}}"
    extension: "json"
    format: "json"
    fields:
      - label: "Jour"
        name: "weekday"
        widget: "select"
        options:
          - label: "Lundi"
            value: "Lundi"
          - label: "Mardi"
            value: "Mardi"
          - label: "Mercredi"
            value: "Mercredi"
          - label: "Jeudi"
            value: "Jeudi"
          - label: "Vendredi"
            value: "Vendredi"
          - label: "Samedi"
            value: "Samedi"
          - label: "Dimanche"
            value: "Dimanche"
      - { label: "Adresse", name: "adress", widget: "string" }
      - { label: "Horaire debut",  name: "hourStart",  widget: "datetime", date_format: false, time_format: "HH:mm" }
      - { label: "Horaire fin",  name: "hourEnd",  widget: "datetime", date_format: false, time_format: "HH:mm" }

  - name: hero
    label: "Infos perso et images"
    folder: "src/content/hero"
    create: true
    extension: "json"
    format: "json"
    fields:
     - { label: "Téléphone", name: "tel", widget: "string" }
     - { label: "Image accueil", name: "heroImg", widget: "image" }
     - { label: "Image savoir faire", name: "historyImg", widget: "image" }
